services:
  vr2ar:
    # build:
    #  context: .
    image: "docker.io/milkjeff/vr2arconverterv3:latest"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "7860:7860"
    ipc: host
