services:
  vr2ar:
    # build:
    #  context: .
    image: "ghcr.io/mastertbo/vr2ar-converter-v3:dispatch-worker"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
    volumes:
      - vr2ar:/jobs
      - process-cache:/app/process
    ports:
      - "7860:7860"
    ipc: host

  vr2ar-worker:
    profiles: ["worker"]
    image: "ghcr.io/mastertbo/vr2ar-converter-v3:dispatch-worker"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      VR2AR_ROLE: worker
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,video
    volumes:
      - vr2ar:/jobs
      - process-cache:/app/process
    ipc: host

volumes:
  vr2ar:
    external: true
  process-cache:

